[package]
name = "coralogix-aws-shipper"
version = "0.0.15"
edition = "2021"


[dependencies]
aws_lambda_events = { version = "0.12.1", default-features = false, features = ["s3", "sns", "cloudwatch_logs"] }
aws-sdk-s3 = "0.35.0"
aws-sdk-sns = "0.35.0"
aws-sdk-cloudwatchlogs = "0.35.0"
aws-config = "0.57.1"
anyhow = "1.0.75"
version = "0.1.0"
lambda_runtime = "0.8.1"
time = "0.3.30"
tokio = { version = "1.34.0", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt","env-filter"] }
tokio-util = "0.7.9"
bytes = "1.0.1"
serde_json = "1.0.64"
serde = { version = "1.0.130", features = ["derive"] }
future-utils = "0.12.1"
futures = "0.3.17"
regex = "1.5.4"
reqwest ="0.11.4"
openssl = { version = "0.10.35", features = ["vendored"] }
cx_sdk_core = { git = "ssh://git@github.com/coralogix/coralogix-sdk-rust" }
cx_sdk_rest_logs = { git = "ssh://git@github.com/coralogix/coralogix-sdk-rust" }
any_vec = "0.13.0"
itertools = "0.11.0"
fancy-regex ="0.12.0"
flate2 = "1.0"
thiserror = "1.0.40"
aws-sdk-secretsmanager = "0.35.0"
derive_more = "0.99.17"

[dev-dependencies]
pretty_assertions_sorted = "1.2.1"
