AWSTemplateFormatVersion: 2010-09-09
Description: The module will create a role with an inline policy to allow Coralogix to send events to an EventBridge event bus.
Parameters:
  EventBusArn:
    Type: String
    Description: The ARN corresponding to the Event Bus that will receive events via the PutEvents method.
    AllowedPattern: '^arn:aws[\w-]*:events:[a-z]{2}-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/[\.\-_A-Za-z0-9]+$'
    MaxLength: 2048
  RoleName:
    Type: String
    Description: Don't change it! It needs to match the one that was input on the Coralogix form. Corresponds to the name of the AWS IAM role that will be created.
    AllowedPattern: '^[a-zA-Z0-9_+=,.@-]+$'
    MaxLength: 64
  CoralogixRegionAlias:
    Type: String
    Description: The Alias for the Coralogix region, possible options are [us1, us2, eu1, eu2, ap1, ap2, custom]
    AllowedValues:
      - us1
      - us2
      - eu1
      - eu2
      - ap1
      - ap2
      - custom
  CustomCoralogixAccount:
    Type: String
    Description: In case you want to use a custom coralogix account, enter the aws account id that you want to use.
    Default: ''
  CustomCoralogixRole:
    Type: String
    Description: In case you want to use a custom coralogix role, enter the role name that you want to use.
    Default: ''
Conditions:
  IsRegionUs2: !Equals
    - Ref: CoralogixRegionAlias
    - us2
  IsCustomAccount: !Not
    - !Equals
      - Ref: CustomCoralogixAccount
      - ''
  IsCustomCoralogixRole: !Not
    - !Equals
      - Ref: CustomCoralogixRole
      - ''
Resources:
  CoralogixEventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role for Coralogix to send events to EventBridge.
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub
                - 'arn:aws:iam::${aws_account_id}:role/${role_name}'
                - aws_account_id: !If
                    - IsCustomAccount
                    - !Ref CustomCoralogixAccount
                    - !If
                      - IsRegionUs2
                      - '739076534691'
                      - '625240141681'
                  role_name: !If
                    - IsCustomCoralogixRole
                    - !Ref CustomCoralogixRole
                    - !Sub 'alerts-eventbus-${CoralogixRegionAlias}'
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CoralogixEventBridgeRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: !Ref EventBusArn
