name: Push File

on: push

jobs:

  job2:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: Filter Changed Files
        id: filtered-files
        run: |
          string="${{ steps.changed-files.outputs.all_changed_files }}"
          result=()
          chmod +x code.sh
          # Split the string into an array using whitespace as the delimiter
          read -ra array <<< "$string"

          # Loop through the array elements
          for element in "${array[@]}"; do
            if [[ $element == aws-integrations/* ]]; then
              integration=$(echo "$element" | xargs -n1 dirname | xargs -n1 basename)
              result+=("$integration")
            fi
          done
          mkdir integrations/
          for element in "${result[@]}"; do
            ./code.sh aws-integrations/lambda-integrations/$element/template.yaml $element
            mkdir integrations/$element/v0.0.1/
            mv aws-integrations/lambda-integrations/$element/template.yaml integrations/$element/v0.0.1/
          done

      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.DESTINATION_REPO_TOKEN }}
        with:
          source_folder: 'integrations'
          destination_repo: 'guyrenny/test'
          # destination_folder: 'modules'
          destination_head_branch: 'branch-name'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          user_name: 'github-actions[bot]'


  # Get-matrix:
  #   runs-on: ubuntu-latest
  #   if: github.event.pull_request.merged == true
  #   outputs:
  #     packages: ${{ env.packages }}
  #   steps:

  #   - uses: actions/checkout@v2
  #   - name: Read matrix YAML
  #     id: read-matrix
  #     run: |
  #       export PACKAGES=$(jq -r '.[].name' matrix.js | jq -rcnR '[inputs]')
  #       echo "packages=$PACKAGES" >> $GITHUB_ENV



