name: validate version

on: 
  pull_request:
    types: [opened, synchronize]
    branches: [master,main]
    paths:
      - "**/template.yaml"
      - "**/cargo.toml"
jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: upload files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: change branch
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull origin master
          echo pull
          git fetch origin
          echo fetch
          echo branch_name_${{ github.head_ref }}
          branch_name=${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          echo "branch_name=$branch_name" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.DESTINATION_REPO_TOKEN }}

      - name: check versions
        run: |
          git branch
          cargo_version=$(cat aws-integrations/aws-shipper-lambda/crago.toml | grep "^version" | head -1 | awk -F '"' '{print $2}')
          template_version=$(cat aws-integrations/aws-shipper-lambda/template.yaml | grep "SemanticVersion" | grep -oE '[^ ]+$')
          if [[ "$cargo_version" != "$template_version" ]];then
            echo "The template and the cargo files are NOT in the same version"
            sed -i '' "/^\[package\]$/,/version =/ s/version = \"[^"]*\"/version = \"$template_version\"/" aws-integrations/aws-shipper-lambda/crago.toml
          else
            echo "The template and the cargo files are in the same version"
          fi
          git add .
          echo branch_name_is_${{env.branch_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.DESTINATION_REPO_TOKEN }}


      - name: update the version
        uses: planetscale/ghcommit-action@v0.1.19
        with:
          commit_message: "align template version with cargo.toml version"
          repo: guyrenny/guy-renny-cloudformation
          branch: ${{env.branch_name}}
          file_pattern: '*.yaml *.toml'
        env:
          GITHUB_TOKEN: ${{secrets.DESTINATION_REPO_TOKEN}}